
name: Lighthouse from reusable workflow

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main ]
jobs:
  lighthouse-scores:

    uses: basantPayU/security-headers-check-github-action/.github/workflows/web-vitals.yml@main
    # uses: basantPayU/security-headers-check-github-action/.github/workflows/web-vitals.yml@main
    # uses: basantPayU/security-headers-check-github-action@tryout
    # uses: paysense-india-services/reusable-workflow/.github/workflows/security-review-cron.yml@main
    with:
      url: https://sandbox-web.lazypay.in/
    secrets: inherit

  add-lighthouse-badges:
    uses: basantPayU/security-headers-check-github-action/.github/workflows/lighthouse-badger-easy.yml@main
    with:
      url: https://sandbox-web.lazypay.in/
      token: "LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN"
      branch: main
    secrets: inherit  
        