name: Lighthouse
on:
  pull_request:
    types: [opened, reopened]
    branches: [ main ]
    
permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  lighthouse-mobile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@v10.0.0
      id: lighthouseCheck
      with:
        urls: 'https://google.com'
        # urls: 'https://sandbox-web.lazypay.in'
        prCommentEnabled: true
        gitHubAccessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        device: mobile

    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "50"
        minBestPracticesScore: "50"
        minPerformanceScore: "20"
        minProgressiveWebAppScore: "50"
        minSeoScore: "50"  
        # - name: Lighthouse Check
        # uses: 
      
  # lighthouse-desktop:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Lighthouse
  #     uses: foo-software/lighthouse-check-action@master
  #     id: lighthouseCheck
  #     with:
  #       urls: 'https://sandbox-web.lazypay.in'
  #       accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
  #       device: desktop
  #       # slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}

  #   - name: Verify Lighthouse Check results
  #     uses: foo-software/lighthouse-check-status-action@master
  #     with:
  #       lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
  #       minAccessibilityScore: "50"
  #       minBestPracticesScore: "50"
  #       minPerformanceScore: "20"
  #       minProgressiveWebAppScore: "50"
  #       minSeoScore: "50"          