# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: production_node_workflow

on:
  pull_request:
    types: [opened, reopened]

permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write    

jobs:      
  test_response_headers:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }} #required to slack post
    # outputs:
    #   rating: ${{ steps.security-check.outputs.rating }}
    steps:
      - name: response-header-security-check
        id: security-check
        uses: basantPayU/security-headers-check-github-action@tryout
        # uses: basantPayU/security-headers-check-github-action@main
        # uses: paysense-india-services/LPWEB-SecurityHeaderAction@main
        with:
          url: 'https://sbox-securepsweb.paysense.io/mobile/terms'
        # run: |
        #   echo "rating=$rating" >> $GITHUB_OUTPUT  
      - name: 'Comment on PR'
        id: security-check-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('the output is bazinga', "${{ steps.security-check.outputs.rating }}")
            const allSecurityHeaderPresent = "${{ steps.security-check.outputs.rating }}" ===  "success"
            const msg = allSecurityHeaderPresent ? "All security header present 🚀 " :  "Security Header missing, please check action for more details"
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
      - name: "check"
        id: check
        run: |
          code=1
          if [[ ${{ steps.security-check.outputs.rating }} == "success" ]]; then
            code=0
          fi
          exit code
#check the output of steps.security-check and pass/fail the action