# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: production_node_workflow

on:
  pull_request:
    types: [opened, reopened]

permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write    

jobs:      
  test_response_headers:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }} #required to slack post

    steps:
      - name: response-header-security-check
        id: security-check
        uses: basantPayU/security-headers-check-github-action@main
        # uses: paysense-india-services/LPWEB-SecurityHeaderAction@main
        with:
          url: 'https://sandbox-web.lazypay.in/needhelp'
          output: rating 
      - name: 'Comment on PR'
        id: security-check-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('the output is', "${{ steps.security-check.outputs.rating }}")
            const allSecurityHeaderPresent = "${{ steps.security-check.outputs.rating }}" ===  "success"
            const msg = allSecurityHeaderPresent ? "+ All security header present 🚀 " : "- Security Header missing, please check action for more details"
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "```diff +hello daisy ```"
                
            })

        # with:
        #   github-token: ${{secrets.GITHUB_TOKEN}}
        #   script: |
        #     const allSecurityHeaderPresent = `{{ steps.security-check.outputs.rating }}`=== "success"
        #     const msg = allSecurityHeaderPresent ? 'All security header present 🚀' : 'Security Header missing, please check action form more details '
        #     github.issues.createComment({
        #       issue_number: context.issue.number,
        #       owner: context.repo.owner,
        #       repo: context.repo.repo,
        #       body: '👋 Thanks for reporting!'
        #     })
      # - uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     message: ${{ steps.coverage.outputs.report }}     
      # - name: checking if output is available
      #   id: check-output
      #   run: echo "${{ steps.security-check.outputs.rating }}"
       
    

